### ISSUE TITLE
module 'nmap' has no attribute 'PortScanner'

### ISSUE THREAD

**Issue by thehappydinoa** [UndeadSec/SocialFish#113]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**
When attempting to port scan I receive this error message:
```python
AttributeError: module 'nmap' has no attribute 'PortScanner'
``` 

**To Reproduce**
1. Port Scan

**Expected behavior**
An `nmap` Response

**Desktop (please complete the following information):**
 - OS: macOS 10.13.4
 - Browser: Google Chrome
 - Version: sharkNet

**Comment by A1S0N** [comment]
Hello, please try the following:

`python3 -m pip install python-nmap`

**Comment by Dp0407** [comment]
AttributeError: module 'nmap' has no attribute 'portscanner' in windowns.

**Comment by Dp0407** [comment]
AttributeError: module 'nmap' has no attribute 'portscanner' please help me.

**Comment by ihasan-iftekhar** [comment]
> AttributeError: module 'nmap' has no attribute 'portscanner' in windowns.

Just run these commands: 
python -m pip uninstall nmap
python -m pip install python-nmap

**Comment by AnjaniGourisaria** [comment]
pip install nose
pip3 install nose
upgrade pip to latest 
➜  PycharmProjects pip3 install python-nmap    
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-nmap in /usr/local/lib/python3.6/site-packages (0.6.4)
➜  PycharmProjects pip install python-nmap   
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-nmap in /home/raju/.local/lib/python3.9/site-packages (0.6.4)
➜  PycharmProjects
