### ISSUE TITLE
Can't clone Instagram

### ISSUE THREAD

**Issue by ImHasanx** [UndeadSec/SocialFish#170]
while cloning i entered the cloning site as https://www.instagram.com and directing site to a insta account..after that clicking on the link a blank white page with a small instagram logo

**Comment by ashar-7** [comment]
I don't know why they haven't fixed this yet

**Comment by teknoalex** [comment]
i have the same problem

**Comment by JockeRider199** [comment]
Same problem with instagram and snapchat

**Comment by jepunband** [comment]
yeah same prob.

**Comment by mgovoni2018** [comment]
Join the group: same problem :-(

**Comment by Protox-PTX** [comment]
same problem

**Comment by BrodyStone21** [comment]
Same problem, I'm surprised the issue hasn't at least been addressed by someone. I think Instagram and Snapchat have found a way to prevent this by requring a certain page to load before that actual login page although I cant be for sure, your best would be to create your own login page and use that instead of just trying to clone.
