### ISSUE TITLE
SocialFish problem 

### ISSUE THREAD

**Issue by narayanchandrakar** [UndeadSec/SocialFish#33]
one error in python sh: ./Server/ngrok: not executable: 32-bit ELF file

 [*] Ngrok URL:
 [*] Waiting for credentials...

[Fri Apr  6 10:52:48 2018] Failed to listen on 127.0.0.1:80 (reason: Address already in use)

How to solve

**Comment by torch42151** [comment]
Its because that port is in Use (80) 
You can fix it by Changing the port number of SocialFish.py File..
Open it with an Editor and go through to the bottom and you'll see a line like this 

> system('./Server/ngrok http 3000 > /dev/null &')

Change the port number into something like 3000..

Eg :-  system('./Server/ngrok http 3000 > /dev/null &')

Also change this Line...to the same Port number used above

>system("cd Server/www/ && sudo php -S 127.0.0.1:80")

Eg :- system("cd Server/www/ && sudo php -S 127.0.0.1:3000")

That's It !! ... Save the edited file and Start :+1:

**Comment by An0nUD4Y** [comment]
try this one.... https://github.com/An0nUD4Y/SocialFish

**Comment by An0nUD4Y** [comment]
it has many features....

**Comment by narayanchandrakar** [comment]
Thanks
