### ISSUE TITLE
Using ngrok for phishing is a violation of the terms of service.

### ISSUE THREAD

**Issue by ghost** [UndeadSec/SocialFish#348]
Any sort of phishing or use of hacking tools, even if it's just for learning purposes, is not allowed on the ngrok service. Using these tools will result in an immediate ban from the service.

Please remove all references to ngrok from your repo(s).

**Comment by pyx9999** [comment]
Interesting point, but doesn't that goes against the philosophy of free and open source software...

“The freedom to run the program as you wish, for any purpose.”

“The freedom to study how the program works, and change it so it does your computing as you wish"

“The freedom to redistribute copies so you can help others"

“The freedom to distribute copies of your modified versions to others"

**Comment by lee-tschetter-ngrok** [comment]
Not totally sure what you're referring to. Your project may be opensource, but the ngrok commercial product is not opensource software. ngrok has been closed source since the 2.x version was released in 2015: https://github.com/inconshreveable/ngrok/issues/255.

Once again we are asking that you remove ngrok from your repo. ngrok shows an interstitial page ahead of HTML content to warn users about potential malicious content, and we have automated processes to ban users that attempt to use phishing tools on our platform. There are many free and OSS ngrok alternatives you can include in your repo if you so choose.

**Comment by pyx9999** [comment]
I am not the owner of this repo. I am merely an observer friend... 

And, I am referring to the four essential freedoms of open source software. I only know about them b/c I am studying for my lpi essentials certification exam. Check them out if you like.

https://www.gnu.org/philosophy/free-sw.en.html

**Comment by pyx9999** [comment]
And, I don't think the owner of the repo cares what you have to say.
