### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bLoodypRince** [UndeadSec/SocialFish#43]
Hi, When i installing social fish i get this error 
Traceback (most recent call last):
  File "SocialFish.py", line 22, in <module>
    from core.view import *
  File "/root/Desktop/SocialFish-master/core/view.py", line 14, in <module>
    from huepy import *
ModuleNotFoundError: No module named 'huepy'

please help me.

**Comment by JrCK** [comment]
Hi there,

I have a similar issue running this new version on a Raspberry Pi Zero W with a P4wnP1 Kali Linux distro. I have another Kali iso running the old version and it works as expected. 

The ngrok file was downloaded for the arm version to fix the wrong ngrok architecture (in my case) witch the script download (think it's x86)

Here what happen when I run the command python3 SocialFish.py

Traceback (most recent call last):
File "SocialFish.py", line 80, in <module>
    main()
File "SocialFish.py", line 34, in main
    head()
File "/root/Apps/SocialFish/core/view.py", line 54, in head
    ''')))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 285-291: ordinal not in range(128)

What about this unicode error? Have no idea how to fix it, since I'm new with linux distros...

Does anyone can help with this?

**Comment by clouditable** [comment]
the reason for this is the conflict between python 3 version and python 2 version
try setup with pip3

**Comment by A1S0N** [comment]
You must be use Python 3 and PIP 3.

**Comment by bLoodypRince** [comment]
Not working again same error

**Comment by JrCK** [comment]
Same for me. Despite it has been installed with pip3 and run with python3, I've donne this again with the same results.

**Comment by admin121231** [comment]
my error sh: 1: ./base/Server/ngrok: not found what to do in this case?

**Comment by JrCK** [comment]
Hey admin121231,

Based on your system architecture just download the ngrok file from oficial website:

https://ngrok.com/download

If you are running the v1.0, copy the file ngrok to the folder:

/your installation path/Social-Fish/Server/

Don't know if this is correct, since I could not run this new version yet, but based on the source code for the v2.0 the file you downloaded goes to the folder:

/your installation path/Social-Fish/base/Server/

then chmod +x ngrok

Think this could fix this problem. Tell me if this works for you.

I'm going to try a fresh install on a x86 or amd64 kali distro to see if the problem of this new version is because of a missing file from my armv6 distro, then I'll put the results here.

**Comment by JrCK** [comment]
Just installed a fresh install right now on a Kali Linux amd64 architecture using the instructions in the code page (using pip3 and python3) and it works like a charm! Think there's something missing to work correctly in my armv6. Don't know if it's just my armv6 distro or an arm limitation. Hey clouditable, A1S0N, is it compatible with arm distros or I am doing something wrong?

**Comment by A1S0N** [comment]
Hi @JrCK,
Maybe ngrok doesn't working right, I'll check out what are happening in ARM,
Thanks a lot,
Alisson Moretto.

**Comment by Anonmus** [comment]
Hey bro, i was also having the same problem. Here how I solved it.
You need to install 2 packages first is huepy and second is wget. Now for this go to terminal and type
easy_install huepy
easy_install wget
That's it.

**Comment by admin121231** [comment]
I have a terminal Kali linux on Win 10 produces an error sh: 1: ./base/Server/ngrok: not the fund! What to do ?

**Comment by ak121150** [comment]
#Bloodyprince install python 3 not any version. Its really works U cn get from here
https://www.python.org/download/releases/3.0/? install this and  above link also https://bootstrap.pypa.io/get-pip.py  after reinstall all huepy and weget by pip command

**Comment by JrCK** [comment]
Hey @Anonmus , @ak121150 wich distros an them respective architecture are you installing with this instructions? With Kali amd64 I have no trouble at all. Gonna try this instructions in a Raspberry Kali P4wnP1 armv6 distro and when I finish I'll come back here with the results. 

By the way, congratulations to the developers, this is such a nice code. Saudações do Brasil!

**Comment by A1S0N** [comment]
@admin121231 fixed

**Comment by admin121231** [comment]
Hey @A1S0N #
![SocialFish_error](https://user-images.githubusercontent.com/39063124/42725733-a0457ca4-8791-11e8-8402-b5442c562a4d.png)
such an error and left here as proof of a screenshot!

**Comment by A1S0N** [comment]
@admin121231 Please try to clone and run again

**Comment by marbyn** [comment]
================ERROR==========================
Hi, When i installing social fish i get this error
Traceback (most recent call last):
File "SocialFish.py", line 22, in 
from core.view import *
File "/root/Desktop/SocialFish-master/core/view.py", line 14, in 
from huepy import *
ModuleNotFoundError: No module named 'huepy'
===============================================

=========SOLUCION=================
El error viene por instalar -apt-get install requeriments-     <----- error
solución 

==============correct=============
git clone https://github.com/UndeadSec/SocialFish.git
cd SocialFish
sudo apt-get install python3-pip php -y

sudo pip3 install huepy
sudo pip3 install wget
sudo python3 SocialFish.py

Listo  ok
=======================================

![image](https://user-images.githubusercontent.com/36746514/43200146-0e3745e4-8fda-11e8-9b86-52f633b26eb9.png)

**Comment by vaib27** [comment]
![Screenshot_2020-08-02-17-49-01-75](https://user-images.githubusercontent.com/68373711/89122853-7c3b8c80-d4e8-11ea-9bd2-21e62bcad2e0.png)
Can you help me solve this error?

**Comment by VirmerA** [comment]
Im using termux for android, and im stuck with the text, installing ngrok.... What to do?
