### ISSUE TITLE
Facebook page doesn't look like real

### ISSUE THREAD

**Issue by Szymonex0906** [UndeadSec/SocialFish#84]
![screenshot_20181110-141030](https://user-images.githubusercontent.com/34396704/48301713-7a4ec000-e4f2-11e8-80fc-813f06fc946f.png)

**Comment by Aakib321** [comment]
It is because of low internet speed

**Comment by gabyavra** [comment]
Is about JS is not loading. I've also tried on faster internet. I have the same issue 

  Kind Regards,
  Cu respect, 
  Gabriel Avramescu
  Do you need a Network or IT Security training?

 
  http://www.ituniversity.ro
  Twitter: @ITUniversityRO

On 10 Nov 2018, at 15:35, Aaqib <notifications@github.com> wrote:

It is because of low internet speed
